# Snowflake Environment Configuration
# This file is used when the Streamlit app runs in Snowflake

name: streamlit-env
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - streamlit>=1.28.0
  - snowflake-connector-python>=3.6.0 